### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by sessi973** [sessi973/protospace-37466#1]
URL
 https://protospace-37466.herokuapp.com/

**Comment by snkw-works** [comment]
@sessi973 さん、大変お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

##### プロトタイプ投稿機能
- [x] **投稿に必要な情報が入力されていない場合は、投稿できずにそのページに留まるよう修正しましょう**
空欄がある状態で保存ボタンをクリックすると、エラー画面に遷移してしまいます。
<img width="643" alt="スクリーンショット 2022-02-25 9 12 08" src="https://user-images.githubusercontent.com/54050089/155629313-8476a908-3c38-49b4-af19-54609005f4d3.png">

##### プロトタイプ削除機能
- [x] **ログイン状態のユーザーに限り、自身の投稿したプロトタイプの詳細ページから削除ボタンをクリックすると、プロトタイプを削除できるよう修正しましょう**
削除ボタンをクリックするとエラーページに遷移してしまい、削除が完了できない状態です。

##### ユーザー詳細機能
- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するよう修正しましょう**
コメント投稿者名をクリックすると、トップページに遷移してしまいます。

##### その他
- [x] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされるよう修正しましょう**
他のユーザーのプロトタイプ編集ページに遷移できてしまいます。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by sessi973** [comment]
ありがとうございます。　修正終わりましたので　ご確認お願いいたします！

**Comment by snkw-works** [comment]
@sessi973 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、前回お伝えした点について修正が確認できませんでした。
**マージやデプロイ忘れの可能性もございます。** 今一度ご確認をお願いします！

[修正依頼箇所]
##### プロトタイプ投稿機能
- [x] **投稿に必要な情報が入力されていない場合は、投稿できずにそのページに留まるよう修正しましょう**
空欄がある状態で保存ボタンをクリックすると、エラー画面に遷移してしまいます。
<img width="643" alt="スクリーンショット 2022-02-25 9 12 08" src="https://user-images.githubusercontent.com/54050089/155629313-8476a908-3c38-49b4-af19-54609005f4d3.png">

##### プロトタイプ削除機能
- [x] **ログイン状態のユーザーに限り、自身の投稿したプロトタイプの詳細ページから削除ボタンをクリックすると、プロトタイプを削除できるよう修正しましょう**
削除ボタンをクリックするとエラーページに遷移してしまい、削除が完了できない状態です。

##### ユーザー詳細機能
- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するよう修正しましょう**
コメント投稿者名をクリックすると、トップページに遷移してしまいます。

##### その他
- [x] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされるよう修正しましょう**
他のユーザーのプロトタイプ編集ページに遷移できてしまいます。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by mo1015** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、引き続き修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するよう修正しましょう**
コメント投稿者名をクリックすると、そのプロトタイプを投稿したユーザーの詳細ページへ遷移してしまいます。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by sessi973** [comment]
修正いたしました。　よろしくお願いいたします。

**Comment by soll02solglas** [comment]
@sessi973さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
